-- 1. Create the products table
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  price NUMERIC NOT NULL,
  image TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Insert initial mockup data
INSERT INTO products (name, price, image) VALUES
('CyberVR Headset Pro', 299, '/images/product1.png'),
('HoloMech Keyboard', 149, '/images/product2.png'),
('Quantum Energy Core', 499, '/images/product3.png'),
('Neural Gauntlet X', 899, '/images/product4.png');

